apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: fraud-detector
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9000
  selector:
    run: fraud-detector
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fraud-detector
  name: fraud-detector
  namespace: default
spec:
  containers:
    - image: aliok/fraud-detector
      name: fraud-detector
      imagePullPolicy: Always
      ports:
        - containerPort: 9000
      resources: {}
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: fraud-detector
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: com.example.transaction.created
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: fraud-detector

