apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: transaction-logger
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9000
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8000
  selector:
    run: transaction-logger
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: transaction-logger
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
  name: transaction-logger
  namespace: default
spec:
  containers:
    - image: aliok/transaction-logger
      name: transaction-logger
      imagePullPolicy: Always
      ports:
        - containerPort: 9000
        - containerPort: 8000
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: transaction-logger
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: com.example.transaction.checked
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: transaction-logger

